### ISSUE TITLE
输入空白符问题

### ISSUE THREAD

**Issue by linphone-young** [SnailSword/zdjd#2]
输入字符串没有去除左右换行符，人语->o.O有\n直接报错，o.O->人语会根据行数翻译\n为 0.o 、 O_O 、0wo等

**Comment by SnailSword** [comment]
感谢反馈，能给一个“人语->o.O有\n直接报错”的复现例子么？

**Comment by linphone-young** [comment]
> 

抱歉说反了，就是点“人语”时，输入的尊嘟语含有“换行符”会报错“你输入的是假嘟语，请重新输入”。
感觉可以完善一下，多个检查，可以将输入根据空白符切割后再用空格拼接后进一步检错

**Comment by SnailSword** [comment]
尊嘟语里是没有```\n```的，所以有```\n```时鉴定为假嘟语是符合预期的。

你描述的情况可能是从B站评论区或其他地方复制过来时，平台对评论区复制行为有特殊处理。所以为了解决这个问题，我在[翻译器](https://zdjd.vercel.app/)这边做了改动：输入尊嘟语之后会```trim```一下再进行翻译。

**Comment by Rain-0x01-39** [comment]
尊嘟语插入空格和换行符会报错
其实可以忽略所有换行符和空格再解码，~~这样做的话播彩六会更方便~~
